language: node_js

node_js:
  - 10

# Travis-ci cache
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run coverage

after_success:
  - npm run codecov

branches:
  only:
    - master
